name: tekartik_firebase_auth_rest
description: Firebase auth rest
version: 0.9.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  cv:
  uuid: '>=1.0.0'
  path: ">=1.9.0"
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
    version: '>=0.9.0'
  tekartik_firebase_rest:
    git:
      url: https://github.com/tekartik/firebase_rest.dart
      path: firebase_rest
    version: '>=0.8.3'
  googleapis_auth: '>=1.4.0'
  googleapis:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  http:
  yaml: ">=3.1.2"
  fs_shim: ">=2.3.3+1"
  tekartik_browser_utils:
    git: https://github.com/tekartik/browser_utils.dart

dev_dependencies:
  tekartik_firebase_auth_test:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_test
  web: '>=0.5.0'
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: ">=0.10.9+1"
  build_web_compilers: ">=4.0.11"
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.2"
  tekartik_io_auth_utils:
    git:
      url: https://github.com/tekartik/io_auth_utils.dart
    version: '>=0.3.0'

  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase

resolution: workspace
  # tekartik_firebase_auth:
  #  path: ../auth
  # tekartik_firebase_auth_browser:
  #  path: ../auth_browser
  # tekartik_firebase_auth_test:
  #  path: ../auth_test
  # tmp
  # tekartik_firebase_rest:
  #    path: ../../firebase.dart/firebase_rest
