name: tekartik_firebase_ai_logic_rest
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  googleapis_auth: '>=1.4.0'
  googleapis:
  tekartik_firebase_vertex_ai:
    git:
      url: https://github.com/tekartik/firebase_vertex_ai.dart
      path: vertex_ai

dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.25.6"
